config/routes.rb
Rails.application.routes.draw do

  get "static_pages/results"

  get "static_pages/invalid_url"

  root 'static_pages#home'

end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.encoding = "utf-8"
end

app/controllers/static_pages_controller.rb
# encoding: utf-8
include StaticPagesHelper
class StaticPagesController < ApplicationController
	before_action :set_uri, only: :results

  def home
    @languages = Language.all
  end

  def results
  	@extension = get_extension(@uri)
  	if @extension.empty?
  		redirect_to static_pages_invalid_url_path
  	else
  		@raw_uri = get_raw_uri(@uri)
			@code_original = Net::HTTP.get(@uri)
      language_code = Language.find(params[:language]).code
			@code_translated = run_translation(@code_original, @extension, language_code)
		end
  end

  def invalid_url
    @languages = Language.all
	end

	##############################################################################
  private
  	def set_uri
  		begin
	  		@uri = URI(params[:url])
	  	rescue URI::InvalidURIError
	  		redirect_to static_pages_invalid_url_path
	  	end
  	end

  	def get_raw_uri(uri)
  		uri = uri.scheme + "://" + uri.host + uri.path
  		if uri.match(/(https:\/\/github.com\/)|(https:\/\/www.github.com\/)/)
  			uri.gsub!('github.com', 'raw.githubusercontent.com').gsub!('/blob', '')
  		elsif uri.match(/https:\/\/raw.githubusercontent.com\//)
			else
				redirect_to static_pages_invalid_url_path
			end
  		@uri = URI(uri)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
# encoding: utf-8
module StaticPagesHelper
	
	def get_extension(uri)
		File.extname(uri.path)
	end


	# Still need multiline 
	def run_translation(code_original, extension, language_code)
		code_translated = code_original
		translator = MicrosoftTranslator::Client.new('GitATranslation', 'cwzLCkrF5eAIejqfZn8zx/QkDBESQMzo/OO/gzBRGtU=')
		if extension == '.py'
			code_original.split(/(#(.*)\n)|("""(.*)""")/).each do |x|
				if x[0] == "#"
					language = translator.detect(x)
					translated = "#" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				# @TODO does not handle multiline comment
				elsif x.include? "\"\"\""
					x.gsub!("\"\"\"", "")
					language = translator.detect(x)
					translated = translator.translate(x,language, language_code,"text/html")
					code_translated.gsub!(x, translated)
				end
			end
		elsif extension == '.rb'
			code_original.split(/(#.*\n)/).each do |x|
				if x[0] == "#"
					language = translator.detect(x)
					translated = "#" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				end
			end
		elsif ((extension == '.r') || 
			   (extension == '.coffee') || 
			   (extension == '.pl'))
			code_original.split(/(#.*\n)/).each do |x|
				if x[0] == "#"
					language = translator.detect(x)
					translated = "#" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				end
			end
		elsif extension == '.hs'
			code_original.split(/(\-\-.*\n)/).each do |x|
				if x[0] == "\-\-"
					language = translator.detect(x)
					translated = "\-\-" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				end
			end
		elsif extension == '.m'
			code_original.split(/(\%.*\n)/).each do |x|
				if x[0] == "\%"
					language = translator.detect(x)
					translated = "\%" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				elsif x.include? "\.\.\."
					x.gsub!("\.\.\.", "")
					language = translator.detect(x)
					translated = translator.translate(x,language, language_code,"text/html")
					code_translated.gsub!(x, translated)
				end
			end
		elsif extension == '.php'
			code_original.split(/(#.*\n)/).each do |x|
				if x[0] == "#"
					language = translator.detect(x)
					translated = "#" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				elsif x.include? "\/\/"
					x.gsub!("\n", "")
					language = translator.detect(x)
					translated = translator.translate(x,language, language_code,"text/html")
					code_translated.gsub!(x, translated)
				end
			end
		elsif ((extension == '.c') || 
			   (extension == '.java') || 
			   (extension == '.js'))
			code_original.split(/(\/\/.*\n)/).each do |x|
				if x[0] == "\/\/"
					language = translator.detect(x)
					translated = "\/\/" + translator.translate(x,language, language_code,"text/html") + "\n"
					code_translated.gsub!(x, translated)
				end
			end
		else
			redirect_to static_pages_invalid_url_path
		end
		code_translated
	end
end

app/views/layouts/_footer.html.erb
<!-- div.footer -->
<div class="footer navbar-fixed-bottom">
	<div class="row">
	  <a href="https://www.facebook.com/GitATranslation"><i class="fa fa-facebook"></i>&nbsp;</a>
	  <a href="#"><i class="fa fa-twitter"></i>&nbsp;</a>
	  <a href="#"><i class="fa fa-google-plus"></i>&nbsp;</a>
	  <a href="#"><i class="fa fa-linkedin"></i>&nbsp;</a>	
	</div>
</div>
<!-- /div.footer -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="navbar-standard">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitATranslation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Arvo:700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="static_pages_home">

	<!-- div.one -->
	<div class="one">
		<%= render partial: 'layouts/header' %>
		<div class="mid-wrapper">
			<h1 class="mid-heading">Git A Translation</h1>
			<div class="row url-search-form">
				<div class="container">
					<%= form_tag(static_pages_results_path, method: :get) do %>
						<% s = truncate("Link of the GitHub file ex: https://github.com/chi6rag/MediCart/blob/master/db/schema.rb", length: 80) %>
						<%= text_field_tag :url, nil, placeholder: "#{s}" %>
						<%= select_tag :language, options_from_collection_for_select(@languages, "id", "name") %>
						<span class="glyphicon glyphicon-search"></span>
						<%= submit_tag "", data: { disable_with: "" } , class: "hidden" %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="empty-area"></div>
		<div class="bottom-text">
			<h3>Making open source projects on Github more accessible across the world!</h3>
			<p>Git A Translation takes in the url of a Github file and translates the docstrings, comments and other informative features into a language of your choice!</p>
		</div>
		<!-- /.one -->
	</div>

	<div class="row">
		<div class="container" id="two">
		<!-- .two -->
			<div class="matter">
				<h2>Learn More</h2>
				<p>Git a Translation is an open source web application which aims to make open source code more accessible by offering translations of documentation in Github code files. Supports public files on Github; Translations are powered by Microsoft Translate; Application is deployed on Heroku.</p>
			</div>
		<!-- /.two -->
		</div>
	</div>

	<div class="row dummy"></div>

</div>
<%= render partial: 'layouts/footer' %>

app/views/static_pages/index.html.erb
<div class="static_pages_home">

	<!-- div.one -->
	<div class="one">
		<%= render partial: 'layouts/header' %>
		<div class="mid-wrapper">
			<h1 class="mid-heading">Git A Translation</h1>
			<div class="row url-search-form">
				<div class="container">
					<%= form_tag(static_pages_results_path, method: :get) do %>
						<% s = truncate("Link of the GitHub file ex: https://github.com/chi6rag/MediCart/blob/master/db/schema.rb", length: 80) %>
						<%= text_field_tag :url, nil, placeholder: "#{s}" %>
						<%= select_tag :language, options_from_collection_for_select(@languages, "id", "name") %>
						<span class="glyphicon glyphicon-search"></span>
						<%= submit_tag "", data: { disable_with: "" } , class: "hidden" %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="empty-area"></div>
		<div class="bottom-text">
			<h3>Making open source projects on Github more accessible across the world!</h3>
			<p>Git A Translation takes in the url of a Github file and translates the docstrings, comments and other informative features into a language of your choice!</p>
		</div>
		<!-- /.one -->
	</div>

	<div class="row">
		<div class="container" id="two">
		<!-- .two -->
			<div class="matter">
				<h2>Learn More</h2>
				<p>Git a Translation is an open source web application which aims to make open source code more accessible by offering translations of documentation in Github code files. Supports public files on Github; Translations are powered by Microsoft Translate; Application is deployed on Microsoft Azure.</p>
			</div>
		<!-- /.two -->
		</div>
	</div>

	<div class="row dummy"></div>

</div>
<%= render partial: 'layouts/footer' %>

app/views/static_pages/invalid_url.html.erb
<div class="invalid_url">
	<div class="row middle-wrapper">
		<div class="container">
				<!-- .middle_wrapper_left -->
				<div class="col-md-6 middle_wrapper_left">
					<h2>404</h2>
					<p>Invalid URL Entered</p>
					<div class="col-md-offset-2 col-md-8">
						<p class="info">Git A Translation is limited to: <b>
							<ul>
							  <li>C (.c)</li>
							  <li>CoffeeScrip (.coffee)</li>
							  <li>Haskell (.hs)</li>
							  <li>Java (.java)</li>
							  <li>Javascript (.js)</li>
							  <li>Matlab (.m)</li>
							  <li>Perl (.pl)</li>
							  <li>PHP (.php)</li>
							  <li>Python (.py)</li>
							  <li>R (.r)</li>
							  <li>Ruby (.rb)</li>
							</ul>  
						</b>Please make sure that your GitHub file has the corresponding extension. We are working to expand support for more languages.</p>
					</div>
					<dv class="col-md-2"></dv>
				</div>
				<!-- /.middle_wrapper_left -->

				<!-- .middle_wrapper_right -->
				<div class="col-md-6 middle_wrapper_right">
					<h4>Please enter a valid URL</h4>
					<%= form_tag(static_pages_results_path, method: :get) do %>
						<% s = truncate("Link of the GitHub file ex: https://github.com/chi6rag/MediCart/blob/master/db/schema.rb", length: 80) %>
						<%= text_field_tag :url, nil, placeholder: "#{s}" %>
						<%= select_tag :language, options_from_collection_for_select(@languages, "id", "name") %>
						<span class="glyphicon glyphicon-search"></span>
						<%= submit_tag "", data: { disable_with: "" } , class: "hidden" %>
					<% end %>
				</div>
				<!-- /.middle_wrapper_left -->
		</div>
	</div>
	<div class="row dummy"></div>
</div>
<%= render partial: 'layouts/footer' %>

app/views/static_pages/results.html.erb
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&skin=default"></script>
<pre class="prettyprint linenums">
	<%= simple_format(@code_translated, {}, :sanitize => false) %>
</pre>